name: Build

on:
  push:
    branches:
      - ci-cd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7

      - name: Build
        run: docker run --entrypoint '/bin/bash' -v `pwd`:/code/ node:latest -c 'cd /code && yarn install && yarn build'

      - name: upload
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa  # v3.0.1
        with:
          path: dist
