name: Lint and test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint-n-test:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and test
        run: ls -la && docker run --entrypoint '/bin/bash' -v `pwd`:/code/ node:latest -c 'cd /code && yarn install && yarn run lint && yarn test'
